artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/dhanushpittala11/SummarizerText_Hf_End2End_1/raw/main/huggingface_dialogsum_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/huggingface_dialogsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
